name: Build CV

on:
#  push:
#    branches:
#      - main  # Set a branch name to trigger deployment
  workflow_dispatch:        # Enable manual call of this action

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: ðŸ›’ Checkout
        uses: actions/checkout@v4

      - name: âœ¨ Build CV
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            istvan_urban_cv_short.tex
            istvan_urban_cv_tldr.tex
          latexmk_use_xelatex: true

      - name: ðŸš€ Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: compiled
          FOLDER: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
